name: Test build
on:
  pull_request:
    branches:
      - 'main'
jobs:
  test-build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.12.0
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
