name: Test version bump
on:
  pull_request:
    branches:
      - 'main'
jobs:
  test-version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: del-systems/check-if-version-bumped@v1
